name: CI

on:
  push:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_ID: ${{ github.sha }}
    APPLITOOLS_SERVER_URL: https://gannetteyes.applitools.com
    APPLITOOLS_DONT_CLOSE_BATCHES: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: echo "$GITHUB_SHA"
      - run: npm ci
      - run: npm run eyes:setup
      - run: npm run cypress:run
    
  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/
        id: notify
        with:
          batch-id: ${{ env.APPLITOOLS_BATCH_ID }}
          api-key: ${{ env.APPLITOOLS_API_KEY }}
          applitools-server-url: ${{ env.APPLITOOLS_SERVER_URL }}
      - run: if [[ ${{ steps.notify.outputs.response }} == '200' ]]; then echo "HTTP 200 OK received"; else echo "Error code received."; exit 1; fi
