name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_SERVER_URL: ${{ secrets.APPLITOOLS_SERVER_URL }}
    APPLITOOLS_BATCH_ID: ${{ github.sha }}
    APPLITOOLS_DONT_CLOSE_BATCHES: 'true'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run eyes:setup
      - name: Run Tests
        run: npm run cypress:run
    
  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status 
        uses: wei/curl@v1
        with:
          args: -d "" -X POST "$APPLITOOLS_SERVER_URL/api/externals/github/servers/github.com/commit/$APPLITOOLS_BATCH_ID/complete?apiKey=$APPLITOOLS_API_KEY"
