name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_SERVER_URL: 'https://gannetteyes.applitools.com'
    APPLITOOLS_BATCH_ID: ${{ github.sha }}
    APPLITOOLS_DONT_CLOSE_BATCHES: 'true'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run eyes:setup
      - name: Run Tests
        run: npm run cypress:run
    
  batch-completion-notification:
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout2
        uses: actions/checkout@v2
      - name: Update Applitools batch status 
        uses: ./.github/actions/
        id: notify
        with:
          batch-id: ${{ env.APPLITOOLS_BATCH_ID }}
          api-key: ${{ env.APPLITOOLS_API_KEY }}
      - name: Get the Applitools response
        run: if [[ ${{ steps.notify.outputs.response }} == '200' ]]; then echo "HTTP 200 OK received"; else echo "Error code received." > /dev/stderr; fi
